### ISSUE TITLE
Name input

### ISSUE THREAD

**Issue by dylanfevrier** [l-lemaitre/filmsdepleinair#3]
https://github.com/l-lemaitre/filmsdepleinair/blob/623171481fafb885917c359da678229ca4b0ed86/registration.html#L58-L256

:warning: Tes inputs n'ont pas d'attributs `name`. C'est important de les ajouter pour que ton formulaire soit valide, même si dans ce cas, il ne sera pas réellement traité

**Comment by l-lemaitre** [comment]
Merci pour les retours, ils étaient aussi indispensables qu'utiles.
